import Head from 'next/head'
import styles from '../styles/Home.module.css'
import mental from '../public/animations/mental-wellbeing.json'
import { Player } from '@lottiefiles/react-lottie-player';
import Link from "next/link";
import { css, cx } from '@emotion/react'
import {Button} from "@mui/material";
import Image from 'next/image'
import TrendsImg from "../public/search-volume.png"

export default function Home() {

  const divStyles = css`
  	padding: 14px;
  `

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          EMDR animations tests
        </h1>

        <p className={styles.description}>
          EMDR (Eye Movement Desensitization and Reprocessing) is a psychotherapy that enables people to heal from the symptoms and emotional distress that are the result of disturbing life experiences.  Repeated studies show that by using EMDR therapy people can experience the benefits of psychotherapy that once took years to make a difference.
        </p>

        <Player
            autoplay
            src={mental}
            style={{ height: '400px' }}
        >
          {/*<Controls visible={true} buttons={['play', 'repeat', 'frame', 'debug']} />*/}
        </Player>

        <br/><br/><br/>
        <Button variant="contained">
          <Link href="/emdr">
            See Our EMDR therapy tests
          </Link>
        </Button>
        <br/><br/><br/>

        <h1 className={styles.subtitle}>
          Who can benefit from EMDR therapy?
        </h1>
        <p className={styles.paragraph}>
          EMDR therapy helps children and adults of all ages. Therapists use EMDR therapy to address a wide range of challenges: </p>


        <ul>
          <li>Anxiety, panic attacks, and phobias</li>
          <li>Chronic Illness and medical issues</li>
          <li>Depression and bipolar disorders</li>
          <li>Dissociative disorders</li>
          <li>Eating disorders</li>
          <li>Grief and loss</li>
          <li>Pain</li>
          <li>Performance anxiety</li>
          <li>Personality disorders</li>
          <li>PTSD and other trauma and stress-related issues</li>
          <li>Sexual assault</li>
          <li>Sleep disturbance</li>
          <li>Substance abuse and addiction</li>
          <li>Violence and abuse</li>
        </ul>
        <br/><br/><br/>
        <h1 className={styles.subtitle}>
          How popular is it?
        </h1>
        <p className={styles.paragraph}>
          Take a look at the google trends data
        </p>

        <Image
            src={TrendsImg}
            alt="Picture of the author"
            // width={500} automatically provided
            // height={500} automatically provided
            // blurDataURL="data:..." automatically provided
            // placeholder="blur" // Optional blur-up while loading
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          EMDR DEMO - IH Hackathon 2022
        </a>
      </footer>
    </div>
  )
}
